version: '3'
services:
  backend:
    image: mattchevy/leagueapp-backend:latest
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=${MONGO_URI}
      - RIOT_API_KEY=${RIOT_API_KEY}
    restart: always

  frontend:
    image: mattchevy/leagueapp-frontend:latest
    ports:
      - '80:80'
    restart: always
